### PR TITLE
Feature: API V2 Customize Swagger UI 

### LINKED ISSUE #15: Clicking Gear Heart logo on swagger api causes swagger api to break
Steps
--------

1. Go to the api docs endpoint
2. Click the gear heart icon

Expected
-------------
Something positive would happen

Actual
---------
A cross domain error appears, then all requests to those endpoints are 500s until the server is reset

@samanehsan

### PR DESCRIPTION
**Pull request by samanehsan**
Remove the broken gear link and make the Swagger UI OSF-themed. Resolves #15: 
screen shot 2015-05-05 at 11 32 01 am

### CODE REVIEW

**Comment by brianjgeiger** [comment]
Is this the minimal number of files we need to add in order to make this work? Or, to put another way, can we use the pip-installed stuff for everything except a few template files, or do we need to have the whole rest_framework_swagger directory added separately?

**Comment by samanehsan** [comment]
@brianjgeiger now, only the `api/static/rest_framework_swagger/css` and `api/templates` directories are getting tracked. And running `python manage.py collectstatic` does not override those files.

**Comment by brianjgeiger** [comment]
That looks much better :bird:

**Comment by samanehsan** [comment]
Great! Let me know if I need to make any more changes :sunny:

**Pull request merged**
